### ISSUE TITLE
表单验证怎么做

### ISSUE THREAD

**Issue by serrt** [karsonzhang/fastadmin#1]
后台的表单验证，怎么没有

**Comment by karsonzhang** [comment]
这个一直都有考虑，后期肯定会加上的，因为目前增删改查可通过CRUD一键来实现，验证也必然属于其中的一块，有好的想法欢迎一起探讨，QQ群：636393962

**Comment by karsonzhang** [comment]
@serrt 已经加上验证，使用的是nice-validator
