### ISSUE TITLE
没有数据库

### ISSUE THREAD

**Issue by guozhisong** [karsonzhang/fastadmin#12]
没有数据库结构，能不能分享一下。

**Comment by vsery** [comment]
并没有绑定固定的库.
你建个空数据库.给个ROOT账户权限.
启动服务端服务.文件放在根目录.
浏览器流浪时,会跑Public/install.php

**Comment by guozhisong** [comment]
意思是说代码会自动执行创建表结构是吧

**Comment by karsonzhang** [comment]
@guozhisong 执行install.php会自动创建数据库和导入数据表，也可以自己手动导入SQL文件，具体请查看：[http://doc.fastadmin.net/docs/faq.html#FastAdmin的数据库SQL文件在哪里](http://doc.fastadmin.net/docs/faq.html#FastAdmin的数据库SQL文件在哪里)
