### ISSUE TITLE
关于Bower

### ISSUE THREAD

**Issue by qiqizjl** [karsonzhang/fastadmin#15]
根据BowerBlog中的Blog中，官方将Yarn作为Bower替代的前端依赖管理工具。
报错在安装bower的时候也会出现对应的报错
`
npm install -g bower
`
`
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
`
现在看起来很像Bower放弃维护了。
目前对于这个项目来说，是否会对Bower做出迁移到Yarn上或者是npm上。还是会继续使用bower作为依赖。或者后续加入对WebPack的支持呢

**Comment by karsonzhang** [comment]
@qiqizjl bower官方的确是不再维护，不过仍然可以正常使用的。FastAdmin的压缩打包基于r.js进行的。后续会有计划对webpack的支持，谢谢支持！

**Comment by qiqizjl** [comment]
非常感谢您提供那么好的开源项目 Thinks

**Comment by qiqizjl** [comment]
非常感谢您提供那么好的开源项目 Thanks

**Comment by yumindeckard** [comment]
还在用bower ？
