### ISSUE TITLE
使用 install.php 安装提示 当前权限不足，无法写入锁定文件

### ISSUE THREAD

**Issue by F4NNIU** [karsonzhang/fastadmin#2]
使用 install.php 安装提示 当前权限不足，无法写入锁定文件

**Comment by realgaodacheng** [comment]
@F4NNIU 你的是什么操作系统？ 目录及文件的权限可能设置的不对。第一，将你项目的目录及文件的属主及属组改成Web程序的运行者 （`sudo lsof -i:80`通过此命令可以得到此信息），第二，将目录权限改成755，将文件权限改成644(`sudo find /path/to/your/app -type d sudo chmod 755 {} \;`  和 `sudo find /path/to/your/app -type f sudo chmod 644 {} \;` )   如再有问题，请留言。

**Comment by F4NNIU** [comment]
这个问题已经修复.

**Comment by karsonzhang** [comment]
问题已经修复，参考 [35fbc6229cfbe05cc5b857e98368fbb4aea85d00](https://github.com/karsonzhang/fastadmin/commit/35fbc6229cfbe05cc5b857e98368fbb4aea85d00)
