### ISSUE TITLE
 Access denied for user 'root'@'localhost' 

### ISSUE THREAD

**Issue by zxzxzxygithub** [karsonzhang/fastadmin#28]
Access denied for user 'root'@'localhost' 
文档说请确保数据库服务器、用户名、密码配置正确，
这个要在哪里配置？怎么样才算正确？

**Comment by karsonzhang** [comment]
@zxzxzxygithub 你使用的命令行安装的是吧。尝试添加-u 用户名 -p 密码 试试，也可以直接执行install.php进行网页端安装试试。
