### ISSUE TITLE
富文本框无法渲染

### ISSUE THREAD

**Issue by qiao1994** [karsonzhang/fastadmin#32]
现在是textarea已经有了editor这个class，但是依然无法被渲染成富文本框，求解决，感谢~

**Comment by karsonzhang** [comment]
@qiao1994 建议你查看官方文档：http://doc.fastadmin.net/docs/component.html#%E5%AF%8C%E6%96%87%E6%9C%AC%E7%BC%96%E8%BE%91%E5%99%A8-3

**Comment by qiao1994** [comment]
马虎了，非常感谢~
