### ISSUE TITLE
app\common\controller\Backend这个基类的buildparams方法是不是有bug

### ISSUE THREAD

**Issue by lovefisher** [karsonzhang/fastadmin#42]
当设置关联查询的时候 
$name = \think\Loader::parseName(basename(str_replace('\\', '/', get_class($this->model))));
这行代码并无法获取完整表名 假设我的表名有前缀  sql就报错了

**Comment by cicl** [comment]
我已遇到坑了，就不在这里回复一下，解决方法在下面的链接 https://www.edoou.com/articles/1558441800709028

**Comment by karsonzhang** [comment]
目前最新版本已优化。
