### ISSUE TITLE
phpspreadsheet要求php版本大于5.6

### ISSUE THREAD

**Issue by WencoChen** [karsonzhang/fastadmin#47]
看文档上要求php版本大于5.5，那现在5.5是不是就不行了
![image](https://user-images.githubusercontent.com/38133076/56400002-0c1dde80-6284-11e9-9c09-002e01e68d3f.png)
![image](https://user-images.githubusercontent.com/38133076/56400009-117b2900-6284-11e9-8698-487592c24120.png)

**Comment by karsonzhang** [comment]
目前仅支持PHP7+版本
