### ISSUE TITLE
什么时候升级 ThinkPHP5.1 版本

### ISSUE THREAD

**Issue by liaohui5** [karsonzhang/fastadmin#49]
看着 ThinkPHP 5.1 版本的新功能眼馋, 但是ThinkPHP什么都没有, 基本都得自己写, 什么时候能升级到ThinkPHP 5.1 啊

**Comment by cygmris** [comment]
[](https://github.com/cygmris/think2h4ck)
可以试一下这个因为最近有套tp5.1的站需要和fastadmin然后fa还没升级到tp5.1所以升级了一下打算后续根据自己需求再做一些魔改。里面基于tp5的插件如果有坑需要自己填了。不过一般都是加上facade或者去掉collection就好了 还有配置项加上命名空间获取。

**Comment by xqkeji** [comment]
是不是应该thinkphp6.0了？

**Comment by liaohui5** [comment]
> 是不是应该thinkphp6.0了？

ThinkPHP 6.0 还在开发阶段, 都还没正式发布, 所以 5.1是最好的选择,相对稳定, 而且还能体验最新功能

**Comment by hellowzsg** [comment]
@liaohui5 
https://github.com/hellowzsg/fastadmin-thinkphp5.1
基本上已经升级完成了，准备实际项目使用
