### ISSUE TITLE
UCcenter 如何使用的案例（demo）有吗？

### ISSUE THREAD

**Issue by Tinywan** [karsonzhang/fastadmin#5]
UCcenter 如何使用的案例（demo）有吗？

**Comment by karsonzhang** [comment]
代码中的会员登录注册即可使用Ucenter，不过FastAdmin中的Ucenter使用的是修改后的Ucenter，请使用[http://git.oschina.net/karson/ucenter](http://git.oschina.net/karson/ucenter)

**Comment by Tinywan** [comment]
@karsonzhang 非常感谢。
