### ISSUE TITLE
前台使用selectpage

### ISSUE THREAD

**Issue by GtGuiZhou** [karsonzhang/fastadmin#51]
想要在fastadmin的前台使用selectpage，只需要在`fastadmin\public\assets\css\frontend.css`中加入`@import url("../libs/fastadmin-selectpage/selectpage.css");`即可，不能使用的原因是前台引入了selectpage的js文件，但是没有引入css文件，这里引入就行了，如果是BUG希望官方能修复一下。

**Comment by karsonzhang** [comment]
感谢你的反馈。前台CSS可以自行进行引入。
