### ISSUE TITLE
Db事务里面模型操作，事务无效

### ISSUE THREAD

**Issue by yasserli** [karsonzhang/fastadmin#58]
* tp5框架Db事务与模型事务是不同的
* 例子：\application\admin\library\traits\Backend.php里面edit方法，Db::startTrans()开启后一堆模型操作，再Db::rollback()回滚无效
* 这代码块的意义是什么

**Comment by karsonzhang** [comment]
当模型在二级目录时，如果配置了模型的`$connection`时，会导致事务失效。
