### ISSUE TITLE
作者在发送短信和邮件的时候是否用到队列？

### ISSUE THREAD

**Issue by Tinywan** [karsonzhang/fastadmin#6]
##   作者在发送短信和邮件的时候是否用到队列？
+   用户使用邮箱注册的时候会涉及到一个邮箱发送，但是这个邮件发送是同步，导致客户注册时候一直是阻塞的，有什么办法可以不阻塞吗？

**Comment by karsonzhang** [comment]
只能放在队列里面进行异步发送。

**Comment by Tinywan** [comment]
@karsonzhang 我说的是你在项目有试用版的Demo 有没有？

**Comment by karsonzhang** [comment]
@Tinywan 没有的哦。
