### ISSUE TITLE
大佬啥时候更新tp的版本呀

### ISSUE THREAD

**Issue by Faramita2** [karsonzhang/fastadmin#61]
直接升级到tp6怎么样，有这个计划嘛？

**Comment by medmin** [comment]
他们官网都挂了很久了都没修
估计这项目黄了吧？

**Comment by gsons** [comment]
@medmin 黄你妈呢

**Comment by F4NNIU** [comment]
> 他们官网都挂了很久了都没修
> 估计这项目黄了吧？

你好， FastAdmin 可以正常打开的哦，我们一直在努力。
![image](https://user-images.githubusercontent.com/3390878/88123682-fec96f80-cbfd-11ea-81ac-02dbf2660bf9.png)

**Comment by F4NNIU** [comment]
@gsons 友善交流哦，感谢支持 FastAdmin。
