### ISSUE TITLE
新加的表单中的移动如何去掉

### ISSUE THREAD

**Issue by qiqizjl** [karsonzhang/fastadmin#7]
新加的表单中的移动如何去掉

**Comment by karsonzhang** [comment]
@qiqizjl 请具体描述清楚你的问题

**Comment by qiqizjl** [comment]
![image](https://user-images.githubusercontent.com/7540584/29394927-32a1558e-8340-11e7-93a7-c5f4ca8bc64c.png)
我正在基于fastadmin开发自己的CRM平台，但是在更新d7bc9ff之后 在列表中出现了移动按钮。但是我的列表中并不需要这个移动按钮。目前有什么config可以讲其取消么 在某个列表里。

**Comment by karsonzhang** [comment]
@qiqizjl 请使用最新版本，已经修复这个移动按钮出现的BUG
