### ISSUE TITLE
请问在模型事件中返回 false 时定义的自定义错误信息有没有方法在控制器中获取

### ISSUE THREAD

**Issue by jay4497** [karsonzhang/fastadmin#70]
目前在模型事件里直接 `return false`，用户页面只会全部提示为 `No rows were inserted/updated/deleted`，但是事件中 `return false` 肯定是有意义的，怎么能够让用户页面显示出正确的有意义的错误信息？（就是事件里定义一下错误信息，然后 `return false`，最后用户页面就显示出定义的这个错误信息）

**Comment by karsonzhang** [comment]
使用`throw new \think\Exception("发生错误了");`
