### ISSUE TITLE
fastadmin前台getshell漏洞

### ISSUE THREAD

**Issue by cn-panda** [karsonzhang/fastadmin#73]
## 发现者
joseph 

## 影响版本

V1.0.0.20200506_beta

## 利用限制

/application/config.php文件中：

``` php
    //是否开启前台会员中心
    'usercenter'            => true,
```

即需要开启会员中心功能

## 漏洞文件

`/application/index/User.php`文件

第58-67行：

```php
    public function _empty($name)
    {
        $data = Hook::listen("user_request_empty", $name);
        foreach ($data as $index => $datum) {
            $this->view->assign($datum);
        }
        return $this->view->fetch('user/' . $name);
    }
```

此方法中的`$name`参数可控，导致fetch模板注入

攻击者可以利用该漏洞传入包含指定的路径的后门文件，就可以getshell

## 漏洞验证

登陆会员中心，在个人资料页面中修改个人头像：

![001](https://user-images.githubusercontent.com/29268708/93705063-ad315880-fb4c-11ea-995a-b70a49fffa9e.png)

抓包后修改图片数据（满足图片头格式即可）：

![002](https://user-images.githubusercontent.com/29268708/93705069-b5899380-fb4c-11ea-88ce-fa499932d82a.png)

记录下路径后，成功getshell

![003](https://user-images.githubusercontent.com/29268708/93705070-ba4e4780-fb4c-11ea-857a-a23d427d1c41.png)

## 修复建议

对传入进来的`$name`变量做一下过滤

## author
Joseph

## Impact version

V1.0.0.20200506_ beta
##Utilization restrictions
/application/ config.php In the document:

``` php
    //是否开启前台会员中心
    'usercenter'            => true,
```
That is, the member center function needs to be opened

## Vulnerability file

`/application/index/ User.php `Documents
Lines 58-67:

```php
    public function _empty($name)
    {
        $data = Hook::listen("user_request_empty", $name);
        foreach ($data as $index => $datum) {
            $this->view->assign($datum);
        }
        return $this->view->fetch('user/' . $name);
    }
```

The '$name' parameter in this method is controllable, resulting in fetch template injection
The attacker can use this vulnerability to pass in a backdoor file containing the specified path to get shell

## Vulnerability verification
Log in to the member center and modify the personal portrait in the profile page:

![001](https://user-images.githubusercontent.com/29268708/93705063-ad315880-fb4c-11ea-995a-b70a49fffa9e.png)

Modify the image data after capturing the packet (only if the format of the picture header is satisfied)：

![002](https://user-images.githubusercontent.com/29268708/93705069-b5899380-fb4c-11ea-88ce-fa499932d82a.png)

After recording the path, getshell is successful

![003](https://user-images.githubusercontent.com/29268708/93705070-ba4e4780-fb4c-11ea-857a-a23d427d1c41.png)

## Repair suggestions

Filter the incoming '$name' variable

**Comment by karsonzhang** [comment]
感谢反馈。

**Comment by F4NNIU** [comment]
### 修复方法打开`application/index/controller/User.php`，找到大概第`58`行的`_empty`方法，有以下两种修复方法：一种修复方法是直接移除`_empty`方法，另一种是将`_empty`方法改为

 [https://www.fastadmin.net/news/83.html](https://www.fastadmin.net/news/83.html)
